### ISSUE TITLE
New proposal - aixmParser v2.4.0

### ISSUE THREAD

**Issue by BPascal-91** [cquest/aixmParser#4]
Hi Christian,

you have an 'Pull request' open before 2019/12/17... This day, i propose the new version of - aixmParser v2.4.0 ... Please Commit this branch  ;-)

Thank's BPascal

**Comment by BPascal-91** [comment]
He all,

for your information, a last version of aixmParser is open in my repository
https://github.com/BPascal-91/aixmParser

Best regards ; BPascal

**Comment by cquest** [comment]
I've just merged the latest master from your repo with a few fixes.

Thanks for all the additional work !
